export const elements = [
  {
    id: 1,
    name: "CAMARA 1",
    description: "camara de fotos descripcion",
    img: "../img/camara_nikon.jpg",
    category: 1,
    especificaciones: "",
  },
  {
    id: 2,
    name: "CAMARA 2",
    description: "camara de fotos descripcion",
    img: "../img/camara_nikon.jpg",
    category: 1,
    especificaciones: "",
  },
  {
    id: 3,
    name: "CAMARA 3",
    description: "camara de fotos descripcion",
    img: "../img/camara_nikon.jpg",
    category: 1,
    especificaciones: "",
  },
  {
    id: 4,
    name: "FLASH 1",
    description: "flash de zapata descripcion",
    img: "../img/flash_nikon.jpg",
    category: 2,
    especificaciones: "",
  },
  {
    id: 5,
    name: "FLASH 2",
    description: "flash de zapata descripcion",
    img: "../img/flash_nikon.jpg",
    category: 2,
    especificaciones: "",
  },
  {
    id: 6,
    name: "FLASH 3",
    description: "flash de zapata descripcion",
    img: "../img/flash_nikon.jpg",
    category: 2,
    especificaciones: "",
  },
  {
    id: 7,
    name: "LENTE 1",
    description: "lente de fotos descripcion",
    img: "../img/lente_nikon.jpg",
    category: 3,
    especificaciones: "",
  },
  {
    id: 8,
    name: "LENTE 2",
    description: "lente de fotos descripcion",
    img: "../img/lente_nikon.jpg",
    category: 3,
    especificaciones: "",
  },
  {
    id: 9,
    name: "LENTE 3",
    description: "lente de fotos descripcion",
    img: "../img/lente_nikon.jpg",
    category: 3,
    especificaciones: "",
  },
];
